version: "3.8"
services:
    app:
        build: .
        container_name: project_a
        working_dir: /var/www/
        volumes:
            -   ./:/var/www
        networks:
            - app-network

    db:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        env_file:
            -   ./.env
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
